[build]
  base = "."
  command = "npm run build"
  publish = "dist/public"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000
  
[[functions]]
  name = "server"
  runtime = "nodejs18.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200