services:
  - type: web
    name: srilakhmi-traders
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: srilakhmi-data
      mountPath: /opt/render/project/data
      sizeGB: 1